-- FlightSim foundation bootstrap v0.3.0
-- Studio installer: place this Script in ServerScriptService and run once in Studio.
local RS=game:GetService("ReplicatedStorage");local SS=game:GetService("ServerScriptService");local Run=game:GetService("RunService")
local old=RS:FindFirstChild("FlightSim");if old then old:Destroy()end;old=SS:FindFirstChild("FlightSim");if old then old:Destroy()end
local shared=Instance.new("Folder",RS);shared.Name="FlightSim";local rem=Instance.new("Folder",shared);rem.Name="Remotes";local root=Instance.new("Folder",SS);root.Name="FlightSim";local sys=Instance.new("Folder",root);sys.Name="Systems"
local function mod(n,s)local m=Instance.new("ModuleScript");m.Name=n;m.Source=s;m.Parent=sys;return m end
mod("Config",[[return {Aircraft="B737-800",Version="0.3.0",MaxThrust=108000,StartN2=25,MaxAirspeed=360,MaxAltitude=41000,TelemetryRate=20,CommandRateLimit=30,EngineMaxN1=100,HydraulicMax=3000}]])
mod("State",[[local M={};M.__index=M;local function e()return {N1=0,N2=0,EGT=20,OilPressure=0,FuelFlow=0,Thrust=0,Running=false,Starter=false,FuelOn=false,Ignition=false}end;function M.new()return setmetatable({d={Phase="ColdAndDark",Altitude=0,Airspeed=0,Heading=0,Pitch=0,Roll=0,Yaw=0,Position=Vector3.zero,Velocity=Vector3.zero,Throttle={[1]=0,[2]=0},Engines={[1]=e(),[2]=e()},Electrical={Battery=false,ExternalPower=false,APU=false,Bus1=false,Bus2=false},Hydraulic={A=0,B=0},Fuel={Left=10000,Center=10000,Right=10000,Total=30000},Controls={Aileron=0,Elevator=0,Rudder=0,Flap=0,Trim=0},Gear={Nose=true,Left=true,Right=true},Brakes={Parking=true},Avionics={IRS=false,FMC=false,Radios=false,Transponder=false,TCAS=false},Autopilot={Enabled=false,TargetAltitude=0,TargetHeading=0},Failures={}}},M)end;function M:Get()return self.d end;return M]])
mod("Engine",[[local C=require(script.Parent.Config);local M={};M.__index=M;function M.new(s)return setmetatable({s=s},M)end;function M:Step(dt)for _,e in pairs(self.s:Get().Engines)do if e.Starter then e.N2=math.min(60,e.N2+18*dt)else e.N2=math.max(0,e.N2-3*dt)end;if e.Starter and e.FuelOn and e.Ignition and e.N2>=C.StartN2 then e.Running=true end;if not e.FuelOn and e.N2<35 then e.Running=false end;if e.Running then e.N1=math.min(100,e.N1+(100-e.N1)*.8*dt);e.EGT=math.min(910,e.EGT+(650-e.EGT)*1.1*dt);e.OilPressure=math.min(100,e.OilPressure+(80-e.OilPressure)*1.2*dt);e.FuelFlow=e.N1*24;e.Thrust=e.N1/100*C.MaxThrust/2 else e.N1=math.max(0,e.N1-18*dt);e.EGT=math.max(20,e.EGT-90*dt);e.OilPressure=math.max(0,e.OilPressure-30*dt);e.FuelFlow=0;e.Thrust=0 end end end;return M]])
mod("Core",[[local C=require(script.Parent.Config);local M={};M.__index=M;function M.new(s)return setmetatable({s=s},M)end;function M:Step(dt)local x=self.s:Get();local e=x.Electrical;e.Bus1=e.Battery or e.ExternalPower or e.APU or x.Engines[1].Running;e.Bus2=e.Battery or e.ExternalPower or e.APU or x.Engines[2].Running;local r=x.Engines[1].Running or x.Engines[2].Running;x.Hydraulic.A=math.clamp(x.Hydraulic.A+(r and 900 or -450)*dt,0,C.HydraulicMax);x.Hydraulic.B=math.clamp(x.Hydraulic.B+(r and 900 or -450)*dt,0,C.HydraulicMax);local p=e.Bus1 or e.Bus2;x.Avionics.IRS=p;x.Avionics.FMC=p;x.Avionics.Radios=p;x.Avionics.Transponder=p;x.Avionics.TCAS=p;for _,en in pairs(x.Engines)do if en.Running and en.FuelOn then local d=en.FuelFlow*dt/60;x.Fuel.Center=math.max(0,x.Fuel.Center-d/2);x.Fuel.Right=math.max(0,x.Fuel.Right-d/2)end end;x.Fuel.Total=x.Fuel.Left+x.Fuel.Center+x.Fuel.Right end;return M]])
mod("Physics",[[local C=require(script.Parent.Config);local M={};M.__index=M;function M.new(s)return setmetatable({s=s},M)end;function M:Step(dt)local x=self.s:Get();local c=x.Controls;if x.Autopilot.Enabled then local hdgErr=((x.Autopilot.TargetHeading-x.Heading+540)%360)-180;c.Aileron=math.clamp(hdgErr*.015,-.35,.35);local altErr=x.Autopilot.TargetAltitude-x.Altitude;c.Elevator=math.clamp(altErr*.0008,-.18,.18)end;local thrust=x.Engines[1].Thrust+x.Engines[2].Thrust;local throttle=(x.Throttle[1]+x.Throttle[2])*.5;local effective=thrust*(.35+.65*throttle);x.Airspeed=math.clamp(x.Airspeed+(effective/108000*42-x.Airspeed*.020)*dt,0,C.MaxAirspeed);x.Pitch=math.clamp(x.Pitch+c.Elevator*18*dt,-25,25);x.Roll=math.clamp(x.Roll+c.Aileron*35*dt,-60,60);x.Yaw=math.clamp(x.Yaw+c.Rudder*20*dt,-25,25);x.Heading=(x.Heading+x.Yaw*dt)%360;x.Altitude=math.clamp(x.Altitude+x.Airspeed*.514444*math.sin(math.rad(x.Pitch))*dt*3.281,0,C.MaxAltitude);local v=x.Airspeed*.514444;x.Velocity=CFrame.Angles(0,math.rad(x.Heading),0).LookVector*v;x.Position+=x.Velocity*dt;x.Phase=(x.Airspeed<1 and "Ground" or (x.Altitude<50 and "TakeoffOrLanding" or "Airborne"))end;return M]])
local cmd=Instance.new("RemoteEvent",rem);cmd.Name="AircraftCommand";local tel=Instance.new("RemoteEvent",rem);tel.Name="Telemetry";local state=require(sys.State).new();local eng=require(sys.Engine).new(state);local core=require(sys.Core).new(state);local phy=require(sys.Physics).new(state);local last={};local C=require(sys.Config)
local function allowed(p,key,now)local k=tostring(p.UserId)..":"..key;local t=last[k]or 0;if now-t<1/C.CommandRateLimit then return false end;last[k]=now;return true end
cmd.OnServerEvent:Connect(function(p,c,a,b)if type(c)~="string"or not allowed(p,c,os.clock())then return end;local x=state:Get();if c=="Battery"then x.Electrical.Battery=a==true elseif c=="ExternalPower"then x.Electrical.ExternalPower=a==true elseif c=="APU"then x.Electrical.APU=a==true elseif c=="EngineStarter"and(a==1 or a==2)then x.Engines[a].Starter=b==true elseif c=="EngineFuel"and(a==1 or a==2)then x.Engines[a].FuelOn=b==true elseif c=="EngineIgnition"and(a==1 or a==2)then x.Engines[a].Ignition=b==true elseif c=="Throttle"and(a==1 or a==2)then x.Throttle[a]=math.clamp(tonumber(b)or 0,0,1)elseif c=="Control"and(a=="Elevator"or a=="Aileron"or a=="Rudder")then x.Controls[a]=math.clamp(tonumber(b)or 0,-1,1)elseif c=="Flap"then x.Controls.Flap=math.clamp(tonumber(a)or 0,0,1)elseif c=="Gear"then local v=a==true;x.Gear.Nose=v;x.Gear.Left=v;x.Gear.Right=v elseif c=="ParkingBrake"then x.Brakes.Parking=a==true elseif c=="AP"then x.Autopilot.Enabled=a==true elseif c=="APTarget"then x.Autopilot.TargetAltitude=math.clamp(tonumber(a)or 0,0,C.MaxAltitude);x.Autopilot.TargetHeading=(tonumber(b)or x.Heading)%360 end end)
local acc=0;Run.Heartbeat:Connect(function(dt)dt=math.min(dt,.05);eng:Step(dt);core:Step(dt);phy:Step(dt);acc+=dt;if acc>=1/C.TelemetryRate then acc=0;tel:FireAllClients(state:Get())end end);print("[FlightSim] 0.3.0 foundation online")
