-- FlightSim client: cockpit/input + instrument display layer v1.5
-- Place this LocalScript in StarterPlayerScripts.
local Players=game:GetService("Players"); local UserInputService=game:GetService("UserInputService"); local RunService=game:GetService("RunService")
local player=Players.LocalPlayer; local remotes=game:GetService("ReplicatedStorage"):WaitForChild("FlightSim"):WaitForChild("Remotes"); local command=remotes:WaitForChild("AircraftCommand"); local telemetry=remotes:WaitForChild("Telemetry")
local gui=Instance.new("ScreenGui"); gui.Name="FlightSimInstruments"; gui.ResetOnSpawn=false; gui.Parent=player:WaitForChild("PlayerGui")
local panel=Instance.new("Frame"); panel.Name="PFD"; panel.Size=UDim2.fromOffset(420,430); panel.Position=UDim2.new(0,18,1,-448); panel.BackgroundTransparency=0.12; panel.Parent=gui
local title=Instance.new("TextLabel"); title.Size=UDim2.new(1,0,0,30); title.BackgroundTransparency=1; title.Text="B737-800  •  FLIGHT DECK"; title.TextSize=18; title.Font=Enum.Font.GothamBold; title.TextXAlignment=Enum.TextXAlignment.Left; title.Parent=panel
local readout=Instance.new("TextLabel"); readout.Name="Readout"; readout.Position=UDim2.fromOffset(12,36); readout.Size=UDim2.new(1,-24,1,-48); readout.BackgroundTransparency=1; readout.TextSize=14; readout.Font=Enum.Font.Code; readout.TextXAlignment=Enum.TextXAlignment.Left; readout.TextYAlignment=Enum.TextYAlignment.Top; readout.Text="WAITING FOR SIMULATION..."; readout.Parent=panel
local help=Instance.new("TextLabel"); help.Size=UDim2.new(0,620,0,160); help.Position=UDim2.new(1,-638,1,-178); help.BackgroundTransparency=0.18; help.TextSize=13; help.Font=Enum.Font.Gotham; help.TextXAlignment=Enum.TextXAlignment.Left; help.TextYAlignment=Enum.TextYAlignment.Top; help.Text="INPUT\nW/S elevator   A/D aileron   Q/E rudder   Z/C nose-wheel\nF flap   G gear   B parking brake   1/2 starter   R/T fuel   Y/U ignition\nP battery   O APU   L AP   J A/T   X TOGA/go-around\nM/N MCP speed -/+5   K/I MCP VS -/+250\nTraffic display: TA/RA and ATC conflict state are shown when available."; help.Parent=gui
local flap=0; local gearDown=true; local parkingBrake=true; local battery=false; local apu=false; local ap=false; local autoThrottle=false; local mcpSpeed=250; local mcpVS=0
local starter={[1]=false,[2]=false}; local fuel={[1]=false,[2]=false}; local ignition={[1]=false,[2]=false}; local lastControl={Elevator=999,Aileron=999,Rudder=999,NoseWheelSteering=999}; local controlAccumulator=0
local function send(name,a,b) command:FireServer(name,a,b) end
local function updateControls(dt)
 if UserInputService:GetFocusedTextBox() then return end; controlAccumulator+=dt; if controlAccumulator<0.05 then return end; controlAccumulator=0
 local e,a,r,s=0,0,0,0; if UserInputService:IsKeyDown(Enum.KeyCode.W) then e+=1 end; if UserInputService:IsKeyDown(Enum.KeyCode.S) then e-=1 end; if UserInputService:IsKeyDown(Enum.KeyCode.D) then a+=1 end; if UserInputService:IsKeyDown(Enum.KeyCode.A) then a-=1 end; if UserInputService:IsKeyDown(Enum.KeyCode.E) then r+=1 end; if UserInputService:IsKeyDown(Enum.KeyCode.Q) then r-=1 end; if UserInputService:IsKeyDown(Enum.KeyCode.C) then s+=1 end; if UserInputService:IsKeyDown(Enum.KeyCode.Z) then s-=1 end
 local values={Elevator=e,Aileron=a,Rudder=r,NoseWheelSteering=s}; for name,value in pairs(values) do if lastControl[name]~=value then lastControl[name]=value; if name=="NoseWheelSteering" then send(name,value) else send("Control",name,value) end end end
end
UserInputService.InputBegan:Connect(function(input,processed)
 if processed or UserInputService:GetFocusedTextBox() then return end; local k=input.KeyCode
 if k==Enum.KeyCode.P then battery=not battery; send("Battery",battery) elseif k==Enum.KeyCode.O then apu=not apu; send("APU",apu) elseif k==Enum.KeyCode.L then ap=not ap; send("AP",ap) elseif k==Enum.KeyCode.J then autoThrottle=not autoThrottle; send("AutoThrottle",autoThrottle) elseif k==Enum.KeyCode.X then send("GoAround",true)
 elseif k==Enum.KeyCode.M then mcpSpeed=math.clamp(mcpSpeed-5,60,350); send("MCPSpeed",mcpSpeed) elseif k==Enum.KeyCode.N then mcpSpeed=math.clamp(mcpSpeed+5,60,350); send("MCPSpeed",mcpSpeed) elseif k==Enum.KeyCode.K then mcpVS=math.clamp(mcpVS-250,-6000,6000); send("MCPVerticalSpeed",mcpVS) elseif k==Enum.KeyCode.I then mcpVS=math.clamp(mcpVS+250,-6000,6000); send("MCPVerticalSpeed",mcpVS)
 elseif k==Enum.KeyCode.F then flap=(flap==0) and 0.5 or ((flap==0.5) and 1 or 0); send("Flap",flap) elseif k==Enum.KeyCode.G then gearDown=not gearDown; send("Gear",gearDown) elseif k==Enum.KeyCode.B then parkingBrake=not parkingBrake; send("ParkingBrake",parkingBrake)
 elseif k==Enum.KeyCode.One then starter[1]=not starter[1]; send("EngineStarter",1,starter[1]) elseif k==Enum.KeyCode.Two then starter[2]=not starter[2]; send("EngineStarter",2,starter[2]) elseif k==Enum.KeyCode.R then fuel[1]=not fuel[1]; send("EngineFuel",1,fuel[1]) elseif k==Enum.KeyCode.T then fuel[2]=not fuel[2]; send("EngineFuel",2,fuel[2]) elseif k==Enum.KeyCode.Y then ignition[1]=not ignition[1]; send("EngineIgnition",1,ignition[1]) elseif k==Enum.KeyCode.U then ignition[2]=not ignition[2]; send("EngineIgnition",2,ignition[2]) end
end)
telemetry.OnClientEvent:Connect(function(state)
 local e1,e2=state.Engines[1],state.Engines[2]; local gs=state.GroundSteering or {}; local at=state.AutoThrottle or {}; local apState=state.Autopilot or {}; local ei=state.EngineIntegration or {}; local ac=state.ATC or {}; local td=state.TCASDisplay or state.TCAS or {}; local dec=state.ATCDecision or {}
 local messages=ac.LastMessage or ""; if #messages>36 then messages=messages:sub(1,36).."…" end
 local trafficLevel=td.HighestLevel or "NONE"; local trafficText="NONE"; if trafficLevel=="RA" then trafficText="RA" elseif trafficLevel=="TA" then trafficText="TA" end
 local decisionText=dec.Instruction or "NONE"; local intruder=td.ClosestIntruder or dec.ConflictWith or "-"; local range=td.ClosestRangeM or dec.DistanceM or 0
 readout.Text=string.format("PHASE %-14s  ATC %-9s\nALT %6.0f ft  IAS %5.0f kt  HDG %6.1f°\nP/R %5.1f/%5.1f°  VS %6.0f fpm\n\nENG1 N1 %5.1f N2 %5.1f EGT %4.0f RUN %s\nENG2 N1 %5.1f N2 %5.1f EGT %4.0f RUN %s\nASYM %+5.2f  YAWM %+7.3f  OUT %s\n\nELEC BAT %s APU %s BUS %s/%s\nHYD A %4.0f psi B %4.0f psi\nFUEL %7.0f  GEAR %s  FLAP %3.0f%%  BRK %s\nSTEER %s %5.1f°  YAW %5.1f°/s\nAP %s %-10s ALT %6.0f\nA/T %s %-14s SPD %6.0f ERR %+5.1f\nPROT %-10s CMD %.2f/%.2f\n\nATC %s  SQWK %s  READBACK %s\nTRAFFIC %-4s  INTRUDER %-12s  RANGE %5.0fm\nATC DECISION %-14s",state.Phase,ac.Phase or "COLD",state.Altitude,state.Airspeed,state.Heading,state.Pitch,state.Roll,state.VerticalSpeed,e1.N1,e1.N2,e1.EGT,tostring(e1.Running),e2.N1,e2.N2,e2.EGT,tostring(e2.Running),ei.ThrustAsymmetry or 0,ei.YawMoment or 0,tostring(ei.EngineOut),tostring(state.Electrical.Battery),tostring(state.Electrical.APU),tostring(state.Electrical.Bus1),tostring(state.Electrical.Bus2),state.Hydraulic.A,state.Hydraulic.B,state.Fuel.Total,state.Gear.Nose and "DOWN" or "UP",state.Controls.Flap*100,state.Brakes.Parking and "SET" or "OFF",gs.Available and "AVAIL" or "OFF",gs.NoseWheelAngle or 0,gs.YawRate or 0,tostring(apState.Enabled),apState.Mode or "OFF",apState.TargetAltitude or 0,tostring(at.Enabled),at.Mode or "OFF",at.TargetSpeed or 0,at.SpeedError or 0,at.Protection or "NONE",at.ThrottleCommand and at.ThrottleCommand[1] or 0,at.ThrottleCommand and at.ThrottleCommand[2] or 0,messages,ac.Squawk or "2000",tostring(ac.ReadbackValid),trafficText,tostring(intruder),range,decisionText)
end)
RunService.RenderStepped:Connect(updateControls)
