-- FlightSim cockpit annunciation / warning logic v0.4
local Annunciation={}; Annunciation.__index=Annunciation
local function ensure(x) x.Annunciation=x.Annunciation or {}; local a=x.Annunciation; a.MasterWarning=a.MasterWarning or false; a.MasterCaution=a.MasterCaution or false; a.Fire=a.Fire or false; a.Stall=a.Stall or false; a.LowFuel=a.LowFuel or false; a.GearUnsafe=a.GearUnsafe or false; a.FlapOverspeed=a.FlapOverspeed or false; a.HydraulicLow=a.HydraulicLow or false; a.ElectricalLoss=a.ElectricalLoss or false; a.EngineOut=a.EngineOut or false; a.Traffic=a.Traffic or false; a.TrafficTA=a.TrafficTA or false; a.TrafficRA=a.TrafficRA or false; a.ATCConflict=a.ATCConflict or false; a.HoldPosition=a.HoldPosition or false; a.CabinAltitude=a.CabinAltitude or false; a.Pressurization=a.Pressurization or false; a.AntiIce=a.AntiIce or false; a.Messages=a.Messages or {}; return a end
function Annunciation.new(state) return setmetatable({state=state},Annunciation) end
function Annunciation:Step(dt)
 local x=self.state:Get(); local a=ensure(x); local msgs={}; local fp=x.FireProtection or {}; local hyd=x.Hydraulic or {}; local elec=x.Electrical or {}; local gear=x.GearStatus or {}; local fuel=x.Fuel or {}; local engines=x.Engines or {}; local airborne=x.GroundContact~=true; local speed=math.max(tonumber(x.Airspeed) or 0,0); local altitude=math.max(tonumber(x.Altitude) or 0,0); local press=x.Pressurization or {}; local ice=x.AntiIce or {}
 local fire=(fp.MasterFireWarning==true) or ((fp.Engines and ((fp.Engines[1] and fp.Engines[1].Fire) or (fp.Engines[2] and fp.Engines[2].Fire)))==true); local stall=x.StallWarning==true; local gearUnsafe=airborne and speed>120 and gear.DownLocked~=true and altitude<3000; local flapOver=(x.FlapSystem and x.FlapSystem.OverSpeed)==true; local hydraulicLow=airborne and math.max(tonumber(hyd.A) or 0,tonumber(hyd.B) or 0)<900; local electricalLoss=airborne and not (elec.Bus1==true or elec.Bus2==true); local lowFuel=(tonumber(fuel.Total) or 0)<3000; local engineOut=airborne and speed>80 and ((engines[1] and engines[1].Running==false) or (engines[2] and engines[2].Running==false)); local cabinAltitude=press.CabinAltitudeWarning==true; local pressWarning=press.Warning==true; local antiIceWarning=ice.Warning==true
 local t=x.TCAS or {}; local level=t.HighestLevel or "NONE"; local traffic=level~="NONE"; local trafficTA=level=="TA"; local trafficRA=level=="RA"; local decision=x.ATCDecision or {}; local atcConflict=(decision.Instruction or "NONE")~="NONE"; local hold=(decision.Instruction=="HOLD POSITION")
 if fire then table.insert(msgs,"FIRE") end; if stall then table.insert(msgs,"STALL") end; if trafficRA then table.insert(msgs,"TRAFFIC RA") elseif trafficTA then table.insert(msgs,"TRAFFIC TA") end; if atcConflict then table.insert(msgs,"ATC "..tostring(decision.Instruction)) end; if cabinAltitude then table.insert(msgs,"CABIN ALT") elseif pressWarning then table.insert(msgs,"PRESSURIZATION") end; if antiIceWarning then table.insert(msgs,"ANTI-ICE") end; if gearUnsafe then table.insert(msgs,"GEAR UNSAFE") end; if flapOver then table.insert(msgs,"FLAP OVERSPEED") end; if hydraulicLow then table.insert(msgs,"HYDRAULIC LOW") end; if electricalLoss then table.insert(msgs,"ELECTRICAL") end; if lowFuel then table.insert(msgs,"LOW FUEL") end; if engineOut then table.insert(msgs,"ENGINE OUT") end
 a.Fire=fire; a.Stall=stall; a.GearUnsafe=gearUnsafe; a.FlapOverspeed=flapOver; a.HydraulicLow=hydraulicLow; a.ElectricalLoss=electricalLoss; a.LowFuel=lowFuel; a.EngineOut=engineOut; a.Traffic=traffic; a.TrafficTA=trafficTA; a.TrafficRA=trafficRA; a.ATCConflict=atcConflict; a.HoldPosition=hold; a.CabinAltitude=cabinAltitude; a.Pressurization=pressWarning; a.AntiIce=antiIceWarning; a.MasterWarning=fire or stall or gearUnsafe or engineOut or trafficRA or cabinAltitude; a.MasterCaution=(fp.MasterWarning==true and not fire) or flapOver or hydraulicLow or electricalLoss or lowFuel or trafficTA or atcConflict or pressWarning or antiIceWarning; a.Messages=msgs; x.Annunciation=a
end
return Annunciation
