-- Fixed-step simulation clock regression tests v0.2
local Clock=require(script.Parent.SimulationClock)
local function check(ok,msg) assert(ok,msg) end
local function run()
 local c=Clock.new(1/60,16)
 local steps,step,dropped,dt=c:Advance(1/30)
 check(steps==2,"30 Hz frame must execute two 60 Hz simulation steps")
 check(math.abs(step-1/60)<1e-9,"fixed step must remain 60 Hz")
 check(dropped==0,"normal catch-up must not drop simulation time")
 check(math.abs(dt-1/30)<1e-9,"valid frame delta must be preserved")
 steps,_,dropped,dt=c:Advance(0.25)
 check(steps==15,"250 ms frame must execute all required 60 Hz steps within the bounded frame budget")
 check(dropped==0,"250 ms frame must not drop simulation time with 16-step budget")
 check(math.abs(dt-0.25)<1e-9,"frame delta must be capped at 250 ms")
 steps,_,dropped,dt=c:Advance(1.0)
 check(steps==15,"large frame delta must be capped before simulation catch-up")
 check(dropped==0,"capped 1 second frame must not create unbounded catch-up")
 check(math.abs(dt-0.25)<1e-9,"large frame delta must normalize to the 250 ms cap")
 check(c.totalDropped==0,"normal bounded frames must not report dropped simulation time")
 steps,_,dropped,dt=c:Advance(-1)
 check(steps==0,"negative frame delta must not advance simulation")
 check(dropped==0,"negative frame delta must not drop simulation time")
 check(dt==0,"negative frame delta must normalize to zero")
 local safe=Clock.new(1/60,8)
 steps,_,dropped=safe:Advance(0.25)
 check(steps==8,"catch-up must respect the configured maximum substeps")
 check(dropped>0,"excess accumulated time must be explicitly reported as dropped")
 check(safe.totalDropped==dropped,"dropped time must accumulate for diagnostics")
 return true
end
return {Run=run}
